# docker-compose.yml
version: "2"
services:
  api_sgs_form:
    container_name: api_sgs_form
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/api_sgs_form/:/app/fileserver/
    ports:
      - "3434:3434"